import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import SideMenuServer from "@/components/server/SideMenuServer";
import { Providers } from "@/store/provider";

const suse = localFont({
  src: "./fonts/SUSE-VF.ttf",
  variable: "--font-suse",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${suse.variable} antialiased`}>
          {children}
          <SideMenuServer />
        </body>
      </Providers>
    </html>
  );
}
